model:
  type: "GPT2"
  name: "GPT2-Large-BabyLM-100M-Unsloth-CPT"
  hidden_size: 1280
  n_layer: 36
  n_head: 20
  use_pretrained: true
  pretrained_model: "gpt2-large"
  
  # === LoRA Configuration ===
  use_lora: true
  use_qlora: false
  lora_r: 8              # Suggest setting larger (64 or 128) to accommodate new knowledge
  lora_alpha: 16         # Usually rank * 2
  lora_dropout: 0.1
  lora_target_modules: ["c_attn", "c_proj", "c_fc"]
  
  # Unfreeze Embedding layer
  # wte = Word Token Embeddings, lm_head = Output layer
  # In PEFT, putting into modules_to_save will automatically unfreeze and train these layers
  modules_to_save: ["wte", "lm_head"] 

training:
  lr: 2.5e-4              # Normal learning rate for LoRA part
  embedding_lr: 2.5e-5    # Embedding layer learning rate (usually set to 1/10 of lr)
  
  batch_size: 64          # Ensure > gradient_accumulation_steps
  num_epochs: 10           
  gradient_accumulation_steps: 8  # per_device_bsz = 64//8 = 8
  warmup_steps: 300
  fp16: True

logging: 
  output_dir: "./models/"
data:
  tokenizer_path: "gpt2-large"
  train_path: "./corpus_split_100M/train_babylm.txt"
  eval_path: "./corpus_split_100M/val_babylm.txt"
  seq_length: 512
  eval_samples: 8192